# --- Imports --- #
from concurrent.futures import ThreadPoolExecutor

from config import *

# -------
from client import groq_client

from embedding.embeddings import generate_embeddings

from documents.retriever import retrieve_documents
from memory.retriever import retrieve_user_memories

from agents.onboarding_agent import get_response_onboard
from agents.rh_policies_agent import get_response_hr

from memory.memory_manager import generate_conversation_summary, save_summary

# -------
import operator
from typing_extensions import TypedDict
from typing import Annotated
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

from IPython.display import Image, display


# --- Program --- #

class State(TypedDict):
    user_id: str                                            # Collaborator ID (e.g., "collaborator_01")
    last_message: str                                       # Last message
    chat_history: Annotated[list[dict], operator.add]       # Message history of the current conversation
    agent_type: str                                         # Selected agent type ("hr-policies" or "onboarding")
    memories: list[dict]                                    # Previous memories retrieved from Pinecone
    documents: list[dict]                                   # Relevant documents retrieved from Pinecone
    response: str                                           # Response text generated by the agent
    memorize: bool                                          # Flag indicating whether the interaction should be memorized


def classifier(state: State):

    user_message = {"role": "user", "content": state['last_message']}

    system_prompt = f""""You are an intent classifier for HR at TechNova Ltda."
    Classify the user's message into one of the following categories:
    - 'policies': questions about vacations, benefits, working from home,
    schedule, leave, code of conduct, performance reviews, travel, salary, profit sharing.
    - 'onboarding': questions about the first day, checklist,
    admission documents, training, contacts, buddy, probationary period, 
    new employee integration.

    This is VERY IMPORTANT: respond ONLY with the word 'hr-policies' or 'onboarding'."
    """

    chat_completion = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        temperature=0.0,
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": state['last_message']
            }
        ]
    )
    
    agent_type = chat_completion.choices[0].message.content.strip().lower()

    return {"agent_type": agent_type,
            "chat_history": [user_message]}


def retrieve_context(state: State):

    filter_type = state["agent_type"]

    query_embedding = generate_embeddings(state['last_message'])

    def _retrieve_user_memories():
        try:
            return retrieve_user_memories(
                user_id=state["user_id"],
                query_embedding=query_embedding,
                top_k=3)
        except Exception as e:
            print(f"Error in retrieving user memories: {e}")
            return []
        
    
    def _retrieve_documents():
        try:
            return retrieve_documents(
                query_embedding=query_embedding,
                filter_type=filter_type,
                top_k=3
            )
        except Exception as e:
            print(f"Error in retrieving documents: {e}")
            return []
    
    with ThreadPoolExecutor(max_workers=2) as executor:
        future_memory = executor.submit(_retrieve_user_memories)
        future_docs = executor.submit(_retrieve_documents)

        retrieved_memories = future_memory.result()
        retrieved_docs = future_docs.result()

    
    return {"memories": retrieved_memories, "documents": retrieved_docs}


def execute_agent(state: State):

    AGENTS = {
        "onboarding": get_response_onboard,
        "hr-policies": get_response_hr
    }

    agent = state["agent_type"]

    agent_fn = AGENTS[agent]
  
    res = agent_fn(
        query = state['last_message'],
        chat_history = state["chat_history"][:-1],
        documents = state['documents'],
        memories = state['memories']
    )
    
    assistant_message = {"role": "assistant", "content": res["response"]}
    
    return {"response": res['response'],
            "memorize": res['memorize'],
            "chat_history": [assistant_message]}


def save_memories(state: State):

    if state["memorize"] == True:

        summary = generate_conversation_summary(state["chat_history"][-2:])

        save_summary(
            user_id=state['user_id'],
            summary=summary,
            agent_type=state['agent_type']
        )

    return {}


def build_graph():
    workflow = StateGraph(State)

    workflow.add_node("classifier", classifier)
    workflow.add_node("retrieve_context", retrieve_context)
    workflow.add_node("execute_agent", execute_agent)
    workflow.add_node("save_memories", save_memories)

    workflow.add_edge(START, "classifier")
    workflow.add_edge("classifier", "retrieve_context")
    workflow.add_edge("retrieve_context", "execute_agent")
    workflow.add_edge("execute_agent", "save_memories")
    workflow.add_edge("save_memories", END)
    
    memory = MemorySaver()
    
    graph = workflow.compile(checkpointer=memory)
    
    return graph

graph = build_graph()











