# This module manages the long-term memory of agents.
# Memory allows the system to "remember" previous interactions with each user.
# The flow is: conversation → summary via LLM → embedding → storage in Pinecone.
# In the next interaction, relevant memories are retrieved by semantic similarity
# and included in the agent's context, personalizing responses.

"""Long-term memory manager for agents via Pinecone."""

# --- Imports --- #

import uuid
from datetime import datetime, timezone

from config import *

from embedding.embeddings import generate_embeddings
from memory.pinecone_store import upsert_vector

from client import groq_client

from pinecone import Vector

# --- Program --- #

def generate_conversation_summary(messages: list[dict]):

    context = "\n".join(f"{m["role"]}: {m["content"]}" for m in messages)

    user_prompt = f"Make a summary of this conversation:\n{context}"

    system_prompt = f"""
    You are an assistant who generates concise summaries of HR conversations.
    Extract the main points, decisions made, and relevant information in a maximum of 3 sentences. Respond only with the summary.
    """

    chat_completion = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": system_prompt
            },
            {
                "role": "user",
                "content": user_prompt,
            }
        ]
    )

    return chat_completion.choices[0].message.content.strip()


def save_summary(user_id: str, summary: str, agent_type: str):

    """Saves a conversation summary as an embedding in Pinecone.

    The complete memorization flow:

    1. The graph decides whether the interaction should be memorized (flag 'memorize').
    2. The LLM generates a concise summary of the conversation.
    3. This function converts the summary into an embedding and saves it in Pinecone.
    4. In the next interaction, relevant memories are retrieved by similarity.

    Arg:

    user_id: collaborator identifier.

    summary: summarized text of the conversation, generated by the LLM.

    agent_type: which agent generated the response ("hr-policies" or "onboarding").

    topic: first 100 characters of the question (quick reference).

    Returns:

    The unique ID of the saved memory (format: "mem-<12 chars hex>").
    """

    memory_id = f"mem-{uuid.uuid4().hex[:12]}"

    embedding = generate_embeddings(summary)

    timestamp = datetime.now().replace(microsecond=0).isoformat()

    vector = Vector(
        id=memory_id,
        values= embedding,
        metadata= {
            "user_id": user_id,
            "timestamp": timestamp,
            "agent": agent_type,
            "summary": summary
        }
    )

    upsert_vector(vector)
    
    return memory_id